$(document).ready(function(){
    $("#dImage").click(function(){
      $("#dImage").slideDown().hide();
      $("#dDevelopment").show();
    });
    $("#dDevelopment").click(function(){
      $("#dDevelopment").slideUp();
      $("#dImage").slideDown();
    });
  });
  $("#dDevelopment").click(function(){
    $("#dDevelopment").slideUp();
    $("#dImage").slideDown();
  });

$(document).ready(function(){
  $("#dImage").click(function(){
    $("#dImage").slideDown().hide();
    $("#dDesign").show();
  });
  $("#dDesign").click(function(){
    $("#dDesign").slideUp();
    $("#dImage").slideDown();
  });
});

$(document).ready(function(){
  $("#pImage").click(function(){
    $("#pImage").slideDown().hide();
    $("#pManagement").show();
  });
  $("#pManagement").click(function(){
    $("#pManagement").slideUp();
    $("#pImage").slideDown();
  });
});